### ISSUE TITLE
Calculate fields with relevance conditions fail to evaluate

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#133] opened 2021-08-30 22:39 UTC
**To Reproduce**
Form `supervision_with_chw_iccm` in https://github.com/medic/config-muso/pull/418/checks?check_run_id=3463026173#step:6:1297

```
  it('#weird form', async () => {
    await harness.setNow('2000-04-30');
    const noPatientEvaluated = submissionDate => [
      submissionDate ? ['no', submissionDate] : ['yes'],
      ['yes', 'yes'],
      ['yes', 'yes'],
      ['no'],
      [...Array(16).fill('yes')],
      ['yes', 'yes'],
      ['yes'],
      ['Other comments'],
      []
    ];
    const result1 = await harness.fillForm('supervision_with_chw_iccm', ...noPatientEvaluated());
    expect(result1.errors).to.be.empty;
  });
```

**What happened?**
`   AssertionError: expected 'Exception in form-host fillAppForm: FormLogicError: Could not evaluate: /model/instance[1]/supervision_with_chw_iccm/s_patient_evaluation_group/s_patient_evaluation_list/s_taking_other_parameters/has_counted_resp_rate  = \'yes\', message: Cannot read property \'ownerDocument\' of undefined' to be empty`

**What did you expect?**
Can complete form.

**Comment by kennsippell** [comment] 2021-08-31 07:32
This reproduces on cht-core 3.10.5 and is a cht-core issue not a parity issue in the harness.

**Comment by derickl** [comment] 2021-09-01 12:59
This isn't a bug in cht-core. The root cause was linked to having a relevance condition to calculate expression.

This [thread](https://community.kobotoolbox.org/t/calculate-in-dynamic-repeat-activated-despite-skip-giving-error-for-online-submission-edit/15565/28) was quite informative especially [this one](https://community.kobotoolbox.org/t/calculate-in-dynamic-repeat-activated-despite-skip-giving-error-for-online-submission-edit/15565/29)

> If I understand well, it means that ALL calculation types are always “fired”, even in an empty repeat (count 0) or a non-relevant group. So, a relevant clause together with a calculation type NEVER makes sense. Could you confirm, please?

What was weird was that the nodes called out in the error were always in an irrelevant block.

@Marina-Kenf To fix your form, you'd need to delete any relevance expressions on calculate fields and reuse them in the calculation expression.

I'll give an example:

Under `s_tdr_realisation`, 
   we have a calculate field `other_sign` 
   with the following relevance condition `selected(${which_indication_for_tdr}, 'other')`
   and the following calculation expression `${specify_other_indication_for_tdr}`

To fix this, you'd delete the relevance expression and reuse it in the calculation as follows:
   `if(selected(${which_indication_for_tdr}, 'other'), ${specify_other_indication_for_tdr}, '')`

**Comment by derickl** [comment] 2021-09-01 17:53
Investigate parity issue with #78

**Comment by kennsippell** [comment] 2021-09-14 20:01
@derickl In your opinion, should the harness (or pyxform) error/fail tests when there is a relevant condition on a calculate field?

**Comment by derickl** [comment] 2021-09-27 17:48
> should the harness (or pyxform) error/fail tests when there is a relevant condition on a calculate field
Yes. 

>Should form authors be completely avoiding that data combination?
Yes.

**Comment by kennsippell** [comment] 2021-10-01 00:29
@derickl I've opened https://github.com/medic/cht-conf/issues/436. Do you think that would be the correct fix for this? Are there other things the harness could do before closing this issue as duplicate of https://github.com/medic/cht-conf/issues/436?

**Comment by derickl** [comment] 2021-10-04 16:33
Similar class of error https://github.com/medic/cht-conf-test-harness/issues/143. 'Note fields marked as required, will not advance in harness'

**Closed** 2021-11-09 15:52 UTC
