### ISSUE TITLE
"select-contact type-person" drop down widget is failing

### ISSUE THREAD

**Issue by jonathanbataire** [medic/cht-conf-test-harness#230] opened 2023-04-20 09:32 UTC
Form with question of appearance `select-contact type-person` is returning the following error:
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'data')
    at HTMLSelectElement.eval (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/select2/dist/js/select2.js?:5682:25)
    at Function.each (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:381:19)
    at jQuery.fn.init.each (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:203:17)
    at jQuery.fn.init.$.fn.select2 (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/select2/dist/js/select2.js?:5672:14)
    at HTMLSelectElement.eval (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/src/js/enketo/widgets/db-object-widget.js?:48:35)
    at HTMLSelectElement.dispatch (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:5429:27)
    at HTMLSelectElement.elemData.handle (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:5233:28)
    at Object.trigger (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:8715:12)
    at HTMLSelectElement.eval (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:8793:17)
    at Function.each (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:381:19)

``` 
Form example: https://github.com/medic/config-ug-vht/blob/master/forms/app/sdx_notify.xlsx
Test: https://github.com/medic/config-ug-vht/blob/c4ba8c280c6545e14fd7b5c999413bc23b085cf9/test/tasks/smart_discharges_follow_up.spec.js#L81

**Comment by kennsippell** [comment] 2023-04-20 23:07
Dupe of #210

**Closed by kennsippell** 2023-04-20 23:07 UTC
